replicaCount: 1
image:
  repository: harshking/flask-k8s-app
  tag: sha-6147610
  pullPolicy: Always
service:
  type: NodePort
  port: 80
  targetPort: 5000
resources:
  limits:
    cpu: "500m"
    memory: "256Mi"
  requests:
    cpu: "250m"
    memory: "128Mi"
securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
